on: push
name: Testing linkcheck
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: './README.md'
            - name: Send mail
        run-if-failed:
          runs-on: ubuntu-latest
          needs: markdown-link-check
        if: always()
              uses: dawidd6/action-send-mail@v2
              with:
                # mail server settings
                server_address: smtp.gmail.com
                server_port: 465
                # user credentials
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                # email subject
                subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
                # email body as text
                body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                # comma-separated string, send email to
                to: kristi.maask@voco.ee
                # from email name
                from: Github Action
