on: push
name: Testing linkcheck
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: './README.md'
      run-if-failed:
        runs-on: ubuntu-latest
        - name: Send mail

            - uses: dawidd6/action-send-mail@v2
              with:
                server_address: smtp.gmail.com
                server_port: 465
                # user credentials
                username: ${{ secrets.EMAIL_USERNAME }}
                password: ${{ secrets.EMAIL_PASSWORD }}
                subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
                body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
                to: kristi.maask@voco.ee
                from: Github Action
